### ISSUE TITLE
Add brew/cask support

### ISSUE THREAD

**Issue by jeanetienne** [terwanerik/Retini#1]
Add support to install the app from caskroom.io.

**Comment by terwanerik** [comment]
Yes, working on this.

**Comment by jeanetienne** [comment]
Cool, thanks!

**Comment by vitorgalvao** [comment]
What’s the license, though? We could use that, before merging.

**Comment by terwanerik** [comment]
Oh yes sorry, it said that it was not required. MIT license is fine.

**Comment by vitorgalvao** [comment]
Done. This can be closed.
