### ISSUE TITLE
When quality is 10/10, @2x file size will bigger then @3x (jpeg)

### ISSUE THREAD

**Issue by powhu** [terwanerik/Retini#5]
Maybe this is bug of `NSImageCompressionFactor`.

I change the code below fix the problem.

ResizeModel.m 164
```
NSDictionary *properties = quality == 1.0 ? @{} : @{NSImageCompressionFactor : @(quality)};
NSData *data = [bitmapRep representationUsingType:fileType properties:properties];
```

**Comment by terwanerik** [comment]
Ah strange behaviour indeed, might be a but of NSImageCompressionFactor as you mentioned. Pushed a new version out that includes your fixed code. Thanks!
