### ISSUE TITLE
Pixel Art Scaling

### ISSUE THREAD

**Issue by jonellevibe** [terwanerik/Retini#7]
Allow @1x images be enlarged into @2x and @3x images. 
When you make pixel art you create the original size first and then upscale it to look good.

Use the nearest neighbour filtering.

**Comment by terwanerik** [comment]
Yeah might be a nice to have, i'll look into that. Could require the 1x image to explicitly have `@1x` in the filename; otherwise dropping in an entire folder also converts all the converted `@2x`s etc.

**Comment by terwanerik** [comment]
Was an easy fix! Done in v1.3.0 😄
